// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xsZMHztzDFATfur1s6fDND
// Component: _h_EwDMNM90b

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Active from "../../Active"; // plasmic-import: FzDg8WCEpHdu/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_presell_app_test.module.css"; // plasmic-import: xsZMHztzDFATfur1s6fDND/projectcss
import sty from "./PlasmicLeadsContent.module.css"; // plasmic-import: _h_EwDMNM90b/css

createPlasmicElementProxy;

export type PlasmicLeadsContent__VariantMembers = {};
export type PlasmicLeadsContent__VariantsArgs = {};
type VariantPropType = keyof PlasmicLeadsContent__VariantsArgs;
export const PlasmicLeadsContent__VariantProps = new Array<VariantPropType>();

export type PlasmicLeadsContent__ArgsType = {};
type ArgPropType = keyof PlasmicLeadsContent__ArgsType;
export const PlasmicLeadsContent__ArgProps = new Array<ArgPropType>();

export type PlasmicLeadsContent__OverridesType = {
  root?: p.Flex<"div">;
  active?: p.Flex<typeof Active>;
};

export interface DefaultLeadsContentProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLeadsContent__RenderFunc(props: {
  variants: PlasmicLeadsContent__VariantsArgs;
  args: PlasmicLeadsContent__ArgsType;
  overrides: PlasmicLeadsContent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__rEDaY)}>
        <div className={classNames(projectcss.all, sty.freeBox__qbPfU)}>
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__zJ6I)}
            displayHeight={"25px" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"63px" as const}
            loading={"lazy" as const}
            src={{
              src: "/plasmic/presell_app_test/images/trafficsvg.svg",
              fullWidth: 291,
              fullHeight: 150,
              aspectRatio: 1.942857
            }}
          />
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ecUhP
          )}
        >
          {"Traffic"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__zgdcr)}>
        <Active
          data-plasmic-name={"active"}
          data-plasmic-override={overrides.active}
          className={classNames("__wab_instance", sty.active)}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__teoDs
          )}
        >
          {"Processing"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___9WUxH)}>
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img___6U9Lr)}
          displayHeight={"25px" as const}
          displayMaxHeight={"none" as const}
          displayMaxWidth={"100%" as const}
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={"55px" as const}
          loading={"lazy" as const}
          src={{
            src: "/plasmic/presell_app_test/images/leadsIIpng.png",
            fullWidth: 316,
            fullHeight: 168,
            aspectRatio: undefined
          }}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__xorjE
          )}
        >
          {"Leads"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__ec3Rk)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__wrx92
          )}
        >
          {"$5"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__svTpZ
          )}
        >
          {"Daily Budget"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "active"],
  active: ["active"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  active: typeof Active;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLeadsContent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLeadsContent__VariantsArgs;
    args?: PlasmicLeadsContent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLeadsContent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLeadsContent__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLeadsContent__ArgProps,
          internalVariantPropNames: PlasmicLeadsContent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLeadsContent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLeadsContent";
  } else {
    func.displayName = `PlasmicLeadsContent.${nodeName}`;
  }
  return func;
}

export const PlasmicLeadsContent = Object.assign(
  // Top-level PlasmicLeadsContent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    active: makeNodeComponent("active"),

    // Metadata about props expected for PlasmicLeadsContent
    internalVariantProps: PlasmicLeadsContent__VariantProps,
    internalArgProps: PlasmicLeadsContent__ArgProps
  }
);

export default PlasmicLeadsContent;
/* prettier-ignore-end */
