// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xsZMHztzDFATfur1s6fDND
// Component: X5tzWYOKYi5K

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  usePlasmicDataConfig,
  executePlasmicDataOp,
  usePlasmicDataOp
} from "@plasmicapp/react-web/lib/data-sources";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 3VNBKYSN1DZ/component
import Buttonn from "../../Buttonn"; // plasmic-import: vH74q5W3yUX/component
import Footer from "../../Footer"; // plasmic-import: u8qWq0KyHYc/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources"; // plasmic-import: HZxe9asd1Dj/codeComponent

import { useScreenVariants as useScreenVariantsd2JxBvsegxLd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: d2JXBvsegxLD/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_presell_app_test.module.css"; // plasmic-import: xsZMHztzDFATfur1s6fDND/projectcss
import sty from "./PlasmicAds.module.css"; // plasmic-import: X5tzWYOKYi5K/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: q7U0PeZ56jhW/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 50aYXdf2efdU/icon

createPlasmicElementProxy;

export type PlasmicAds__VariantMembers = {};
export type PlasmicAds__VariantsArgs = {};
type VariantPropType = keyof PlasmicAds__VariantsArgs;
export const PlasmicAds__VariantProps = new Array<VariantPropType>();

export type PlasmicAds__ArgsType = {};
type ArgPropType = keyof PlasmicAds__ArgsType;
export const PlasmicAds__ArgProps = new Array<ArgPropType>();

export type PlasmicAds__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultAdsProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAds__RenderFunc(props: {
  variants: PlasmicAds__VariantsArgs;
  args: PlasmicAds__ArgsType;
  overrides: PlasmicAds__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    query: usePlasmicDataOp(
      (() => {
        try {
          return {
            sourceId: "9tDX6QXXin2Z6jndTXctjE",
            opId: "47ff846a-4b02-40e9-9b96-dd91689fd79e",
            userArgs: {
              filters: [$ctx.params.slug]
            },
            cacheKey: "plasmic.$.8e6eFIA0D2zH.$.",
            invalidatedKeys: null,
            roleId: null
          };
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          } else {
            throw e;
          }
        }
      })()
    )
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsd2JxBvsegxLd()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__fuDc1)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__mGs7N)}>
            <div className={classNames(projectcss.all, sty.freeBox__aWmiq)}>
              <div className={classNames(projectcss.all, sty.freeBox__rLhUm)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xxRc9)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Buttonn
                        className={classNames(
                          "__wab_instance",
                          sty.buttonn___6H6Hr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yDzYw
                          )}
                        >
                          {"Add Collaborators"}
                        </div>
                      </Buttonn>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sIlEa
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wwKsZ
                          )}
                          onClick={async event => {
                            const $steps = {};
                            $steps["goToHomepage"] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: __wrapUserFunction(
                                      {
                                        type: "InteractionArgLoc",
                                        actionName: "navigation",
                                        interactionUuid: "iTdH0kg1iXwg",
                                        componentUuid: "X5tzWYOKYi5K",
                                        argName: "destination"
                                      },
                                      () => `/`
                                    )
                                  };
                                  return __wrapUserFunction(
                                    {
                                      type: "InteractionLoc",
                                      actionName: "navigation",
                                      interactionUuid: "iTdH0kg1iXwg",
                                      componentUuid: "X5tzWYOKYi5K"
                                    },
                                    () =>
                                      (({ destination }) => {
                                        __nextRouter?.push(destination);
                                      })?.apply(null, [actionArgs]),
                                    actionArgs
                                  );
                                })()
                              : undefined;
                            if (
                              typeof $steps["goToHomepage"] === "object" &&
                              typeof $steps["goToHomepage"].then === "function"
                            ) {
                              $steps["goToHomepage"] = await __wrapUserPromise(
                                {
                                  type: "InteractionLoc",
                                  actionName: "navigation",
                                  interactionUuid: "iTdH0kg1iXwg",
                                  componentUuid: "X5tzWYOKYi5K"
                                },
                                $steps["goToHomepage"]
                              );
                            }
                          }}
                        >
                          {"Back"}
                        </div>
                        {(
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : true
                        ) ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zkzy7
                            )}
                            onClick={async event => {
                              const $steps = {};
                              $steps["goToSettings"] = true
                                ? (() => {
                                    const actionArgs = {
                                      destination: __wrapUserFunction(
                                        {
                                          type: "InteractionArgLoc",
                                          actionName: "navigation",
                                          interactionUuid: "dIvVGkjyZQPv",
                                          componentUuid: "X5tzWYOKYi5K",
                                          argName: "destination"
                                        },
                                        () =>
                                          `/model/settings/${`value${$ctx.params.slug}`}`
                                      )
                                    };
                                    return __wrapUserFunction(
                                      {
                                        type: "InteractionLoc",
                                        actionName: "navigation",
                                        interactionUuid: "dIvVGkjyZQPv",
                                        componentUuid: "X5tzWYOKYi5K"
                                      },
                                      () =>
                                        (({ destination }) => {
                                          __nextRouter?.push(destination);
                                        })?.apply(null, [actionArgs]),
                                      actionArgs
                                    );
                                  })()
                                : undefined;
                              if (
                                typeof $steps["goToSettings"] === "object" &&
                                typeof $steps["goToSettings"].then ===
                                  "function"
                              ) {
                                $steps["goToSettings"] =
                                  await __wrapUserPromise(
                                    {
                                      type: "InteractionLoc",
                                      actionName: "navigation",
                                      interactionUuid: "dIvVGkjyZQPv",
                                      componentUuid: "X5tzWYOKYi5K"
                                    },
                                    $steps["goToSettings"]
                                  );
                              }
                            }}
                          >
                            {"Settings"}
                          </div>
                        ) : null}
                      </div>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7WgWk
                        )}
                      />
                    ) : null}
                  </div>
                ) : null}
                <div className={classNames(projectcss.all, sty.freeBox__c3PH)}>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___11PzW)}
                      displayHeight={"5rem" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"5rem" as const}
                      loading={"lazy" as const}
                      src={(() => {
                        try {
                          return $queries.query.data[0][
                            "Hero Image (from Products)"
                          ][0].url;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "https://site-assets.plasmic.app/d1fcf223340f5a68156e4b07f6478d57.jpg";
                          }
                          throw e;
                        }
                      })()}
                    />
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__a2Ii)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hLnx
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.query.data[0][
                              "Product Name (from Products)"
                            ][0];
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "LEARNARAMA\u2122 MATS";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                    <Buttonn
                      className={classNames(
                        "__wab_instance",
                        sty.buttonn___2RghU
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__su8F
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.query.data[0][
                                "Brand Name (from Brands)"
                              ][0];
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Unknown Brand";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </Buttonn>
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___387SO)}
                >
                  <Buttonn
                    className={classNames("__wab_instance", sty.buttonn__eIccl)}
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToModel"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: __wrapUserFunction(
                                {
                                  type: "InteractionArgLoc",
                                  actionName: "navigation",
                                  interactionUuid: "ZHTPlEo8wC2r",
                                  componentUuid: "X5tzWYOKYi5K",
                                  argName: "destination"
                                },
                                () =>
                                  `/model/${`recq9fLGvmvRu0wFY${$ctx.params.slug}`}`
                              )
                            };
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "ZHTPlEo8wC2r",
                                componentUuid: "X5tzWYOKYi5K"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToModel"] === "object" &&
                        typeof $steps["goToModel"].then === "function"
                      ) {
                        $steps["goToModel"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "ZHTPlEo8wC2r",
                            componentUuid: "X5tzWYOKYi5K"
                          },
                          $steps["goToModel"]
                        );
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jrfwc
                      )}
                    >
                      {"Pages"}
                    </div>
                  </Buttonn>
                  <Buttonn
                    className={classNames("__wab_instance", sty.buttonn__pZMpw)}
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToAds"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: __wrapUserFunction(
                                {
                                  type: "InteractionArgLoc",
                                  actionName: "navigation",
                                  interactionUuid: "otswRBT6cx0V",
                                  componentUuid: "X5tzWYOKYi5K",
                                  argName: "destination"
                                },
                                () =>
                                  `/model/ads/${`recq9fLGvmvRu0wFY${$ctx.params.slug}`}`
                              )
                            };
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "otswRBT6cx0V",
                                componentUuid: "X5tzWYOKYi5K"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToAds"] === "object" &&
                        typeof $steps["goToAds"].then === "function"
                      ) {
                        $steps["goToAds"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "otswRBT6cx0V",
                            componentUuid: "X5tzWYOKYi5K"
                          },
                          $steps["goToAds"]
                        );
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gLkPn
                      )}
                    >
                      {"Ads"}
                    </div>
                  </Buttonn>
                </div>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__o5Krq)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__y6Pm2)}
                      displayHeight={"2rem" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"2rem" as const}
                      loading={"lazy" as const}
                      src={(() => {
                        try {
                          return $queries.query.data[0][
                            "Icon White Overlay (from Brands)"
                          ][0].url;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "https://site-assets.plasmic.app/d2c8c57202370db27ecf388dfeb366e0.png";
                          }
                          throw e;
                        }
                      })()}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y9RY1
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $queries.query.data[0][
                              "Brand Name (from Brands)"
                            ][0];
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Unknown Brand";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                ) : null}
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i0M2T
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $queries.query.data[0][
                          "Advertorial Ad 1 Newsfeed"
                        ];
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Motor Skills Unlocked With Mat Magic!\n\ud83e\udd38\u200d\u2640\ufe0f Sturdy, Game-changing Mats\n\ud83e\udde0 Boosts Smart Learning!\n\ud83c\udf08 Makes Skills Development Exciting!";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vLxu9)}
                  displayHeight={"20rem" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"20rem" as const}
                  loading={"lazy" as const}
                  src={(() => {
                    try {
                      return $queries.query.data[0][
                        "Advertorial Ad 1 Creative"
                      ][0].url;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "https://site-assets.plasmic.app/e9be12ed60a3b52e2b47a699b5f1087e.jpg";
                      }
                      throw e;
                    }
                  })()}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nn3W
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $queries.query.data[0][
                          "Advertorial Ad 1 Headline"
                        ];
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nkg8
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $queries.query.data[0][
                          "Advertorial Ad 1 Description"
                        ];
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Unfold A Learning Revolution!";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <Buttonn
                  className={classNames("__wab_instance", sty.buttonn__qlsr4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sx2Cp
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.query.data[0][
                            "Advertorial Ad 1 CTA"
                          ][0];
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Learn More";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </Buttonn>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dw79D)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rbz26
                      )}
                    >
                      {"Edit Copy"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Kv9N
                      )}
                    >
                      {"Edit Creative"}
                    </div>
                  </div>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <Buttonn
                    className={classNames("__wab_instance", sty.buttonn__uBosR)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lCDg
                      )}
                    >
                      {"Deploy Assets"}
                    </div>
                  </Buttonn>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__tRdl)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/presell_app_test/images/f49D970E068C4Fdc91FdF19C8458E43Asvg2.svg",
                      fullWidth: 300,
                      fullHeight: 96,
                      aspectRatio: 3.115789
                    }}
                  />
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qpEsy)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                  />
                ) : null}
              </div>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox___0DAjk)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vuEkQ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__u0VAd
                      )}
                      onClick={async event => {
                        const $steps = {};
                        $steps["goToSettings"] = true
                          ? (() => {
                              const actionArgs = {
                                destination: __wrapUserFunction(
                                  {
                                    type: "InteractionArgLoc",
                                    actionName: "navigation",
                                    interactionUuid: "6rYpn7jTePjf",
                                    componentUuid: "X5tzWYOKYi5K",
                                    argName: "destination"
                                  },
                                  () =>
                                    `/model/settings/${`value${$ctx.params.slug}`}`
                                )
                              };
                              return __wrapUserFunction(
                                {
                                  type: "InteractionLoc",
                                  actionName: "navigation",
                                  interactionUuid: "6rYpn7jTePjf",
                                  componentUuid: "X5tzWYOKYi5K"
                                },
                                () =>
                                  (({ destination }) => {
                                    __nextRouter?.push(destination);
                                  })?.apply(null, [actionArgs]),
                                actionArgs
                              );
                            })()
                          : undefined;
                        if (
                          typeof $steps["goToSettings"] === "object" &&
                          typeof $steps["goToSettings"].then === "function"
                        ) {
                          $steps["goToSettings"] = await __wrapUserPromise(
                            {
                              type: "InteractionLoc",
                              actionName: "navigation",
                              interactionUuid: "6rYpn7jTePjf",
                              componentUuid: "X5tzWYOKYi5K"
                            },
                            $steps["goToSettings"]
                          );
                        }
                      }}
                    >
                      {"Settings"}
                    </div>
                    <Buttonn
                      className={classNames(
                        "__wab_instance",
                        sty.buttonn__yzYei
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i0RSj
                        )}
                      >
                        {"Add Collaborators"}
                      </div>
                    </Buttonn>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zuEm)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cOjxm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1KaGl
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Visits"}
                          </span>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7Bb41
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.query.data[0].Visits;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "0";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__q6Gck)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rRKdy
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Leads"}
                          </span>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__z4Jqo
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.query.data[0].Leads;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "0";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uNl1F)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yeqex
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Ad Spend"}
                          </span>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iTyw3
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.query.data[0]["Ad Spend"];
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "$0";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9OlDl
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.query.data[0]["Persona H1"];
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Persona";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zxrYp)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__itl2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__paA5
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Who"}
                          </span>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ufWhz
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.query.data[0]["Persona Who"];
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___3GuWv
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hZTjY
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Problem"}
                          </span>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__miJKb
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.query.data[0]["Persona Problem"];
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Improving children's perceptual motor skills";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7TnWd
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kYdXh
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 600 }}
                          >
                            {"Solution"}
                          </span>
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__adXaG
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $queries.query.data[0]["Persona Solution"];
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Fun, engaging motor skills development";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                  <Buttonn
                    className={classNames("__wab_instance", sty.buttonn__vlh9T)}
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToDeploy"] = true
                        ? (() => {
                            const actionArgs = {
                              destination: __wrapUserFunction(
                                {
                                  type: "InteractionArgLoc",
                                  actionName: "navigation",
                                  interactionUuid: "Kq-xIl0sKKE4",
                                  componentUuid: "X5tzWYOKYi5K",
                                  argName: "destination"
                                },
                                () =>
                                  `/model/deploy/${`value${$ctx.params.slug}`}`
                              )
                            };
                            return __wrapUserFunction(
                              {
                                type: "InteractionLoc",
                                actionName: "navigation",
                                interactionUuid: "Kq-xIl0sKKE4",
                                componentUuid: "X5tzWYOKYi5K"
                              },
                              () =>
                                (({ destination }) => {
                                  __nextRouter?.push(destination);
                                })?.apply(null, [actionArgs]),
                              actionArgs
                            );
                          })()
                        : undefined;
                      if (
                        typeof $steps["goToDeploy"] === "object" &&
                        typeof $steps["goToDeploy"].then === "function"
                      ) {
                        $steps["goToDeploy"] = await __wrapUserPromise(
                          {
                            type: "InteractionLoc",
                            actionName: "navigation",
                            interactionUuid: "Kq-xIl0sKKE4",
                            componentUuid: "X5tzWYOKYi5K"
                          },
                          $steps["goToDeploy"]
                        );
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xzdS
                      )}
                    >
                      {"Deploy Assets"}
                    </div>
                  </Buttonn>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___66Ge0)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/presell_app_test/images/f49D970E068C4Fdc91FdF19C8458E43Asvg.svg",
                      fullWidth: 300,
                      fullHeight: 96,
                      aspectRatio: 3.115789
                    }}
                  />
                </div>
              ) : null}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___0Q9Uw)}>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "footer"],
  header: ["header"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAds__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAds__VariantsArgs;
    args?: PlasmicAds__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAds__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAds__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAds__ArgProps,
          internalVariantPropNames: PlasmicAds__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAds__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAds";
  } else {
    func.displayName = `PlasmicAds.${nodeName}`;
  }
  return func;
}

export const PlasmicAds = Object.assign(
  // Top-level PlasmicAds renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicAds
    internalVariantProps: PlasmicAds__VariantProps,
    internalArgProps: PlasmicAds__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAds;
/* prettier-ignore-end */
